"""Events constants."""
COURIERED = 'couriered'
COURIER_CONFIRMED = 'courier confirmed'
RELAY_REQUIRED = 'relay required'
ESCROW_XDRS_ASSIGNED = 'escrow XDRs assigned'
LAUNCHED = 'launched'
LOCATION_ADDED = 'location added'
LOCATION_CHANGED = 'location changed'
RECEIVED = 'received'
RELAY_XDRS_ASSIGNED = 'relay XDRs assigned'
